// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: censor_check.proto
// Protobuf Java Version: 4.32.0

package ru.alfabank.alfagen.censor.transformation.contract;

@com.google.protobuf.Generated
public final class CensorCheck {
  private CensorCheck() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 32,
      /* patch= */ 0,
      /* suffix= */ "",
      CensorCheck.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_censor_check_MessageText_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_censor_check_MessageText_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_censor_check_MessageList_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_censor_check_MessageList_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_censor_check_Topic_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_censor_check_Topic_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_censor_check_CensorCheckRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_censor_check_CensorCheckRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_censor_check_CensorCheckResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_censor_check_CensorCheckResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022censor_check.proto\022\014censor_check\",\n\013Me" +
      "ssageText\022\017\n\007content\030\001 \001(\t\022\014\n\004role\030\002 \001(\t" +
      "\"7\n\013MessageList\022(\n\005texts\030\001 \003(\0132\031.censor_" +
      "check.MessageText\"*\n\005Topic\022\r\n\005topic\030\001 \001(" +
      "\t\022\022\n\nconfidence\030\002 \001(\002\"\240\001\n\022CensorCheckReq" +
      "uest\022\031\n\021accessDestination\030\001 \001(\t\022\020\n\010syste" +
      "mId\030\002 \001(\t\022\021\n\tmessageId\030\003 \001(\t\022+\n\010messages" +
      "\030\004 \001(\0132\031.censor_check.MessageList\022\035\n\025max" +
      "_completion_tokens\030\005 \001(\005\"\357\001\n\023CensorCheck" +
      "Response\022\031\n\021accessDestination\030\001 \001(\t\022\020\n\010s" +
      "ystemId\030\002 \001(\t\022\021\n\tmessageId\030\003 \001(\t\022+\n\010mess" +
      "ages\030\004 \001(\0132\031.censor_check.MessageList\022\035\n" +
      "\025max_completion_tokens\030\005 \001(\005\022\022\n\nrisk_lev" +
      "el\030\006 \001(\t\022#\n\006topics\030\007 \003(\0132\023.censor_check." +
      "Topic\022\023\n\013explanation\030\010 \001(\t2h\n\022CensorChec" +
      "kService\022R\n\013CensorCheck\022 .censor_check.C" +
      "ensorCheckRequest\032!.censor_check.CensorC" +
      "heckResponseB6\n2ru.alfabank.alfagen.cens" +
      "or.transformation.contractP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_censor_check_MessageText_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_censor_check_MessageText_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_censor_check_MessageText_descriptor,
        new java.lang.String[] { "Content", "Role", });
    internal_static_censor_check_MessageList_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_censor_check_MessageList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_censor_check_MessageList_descriptor,
        new java.lang.String[] { "Texts", });
    internal_static_censor_check_Topic_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_censor_check_Topic_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_censor_check_Topic_descriptor,
        new java.lang.String[] { "Topic", "Confidence", });
    internal_static_censor_check_CensorCheckRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_censor_check_CensorCheckRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_censor_check_CensorCheckRequest_descriptor,
        new java.lang.String[] { "AccessDestination", "SystemId", "MessageId", "Messages", "MaxCompletionTokens", });
    internal_static_censor_check_CensorCheckResponse_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_censor_check_CensorCheckResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_censor_check_CensorCheckResponse_descriptor,
        new java.lang.String[] { "AccessDestination", "SystemId", "MessageId", "Messages", "MaxCompletionTokens", "RiskLevel", "Topics", "Explanation", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
