// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: censor_check.proto
// Protobuf Java Version: 4.32.0

package ru.alfabank.alfagen.censor.transformation.contract;

@com.google.protobuf.Generated
public interface CensorCheckRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:censor_check.CensorCheckRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Значения: "internal" (внутренний) или "external" (внешний)
   * </pre>
   *
   * <code>string accessDestination = 1;</code>
   * @return The accessDestination.
   */
  java.lang.String getAccessDestination();
  /**
   * <pre>
   * Значения: "internal" (внутренний) или "external" (внешний)
   * </pre>
   *
   * <code>string accessDestination = 1;</code>
   * @return The bytes for accessDestination.
   */
  com.google.protobuf.ByteString
      getAccessDestinationBytes();

  /**
   * <code>string systemId = 2;</code>
   * @return The systemId.
   */
  java.lang.String getSystemId();
  /**
   * <code>string systemId = 2;</code>
   * @return The bytes for systemId.
   */
  com.google.protobuf.ByteString
      getSystemIdBytes();

  /**
   * <code>string messageId = 3;</code>
   * @return The messageId.
   */
  java.lang.String getMessageId();
  /**
   * <code>string messageId = 3;</code>
   * @return The bytes for messageId.
   */
  com.google.protobuf.ByteString
      getMessageIdBytes();

  /**
   * <code>.censor_check.MessageList messages = 4;</code>
   * @return Whether the messages field is set.
   */
  boolean hasMessages();
  /**
   * <code>.censor_check.MessageList messages = 4;</code>
   * @return The messages.
   */
  ru.alfabank.alfagen.censor.transformation.contract.MessageList getMessages();
  /**
   * <code>.censor_check.MessageList messages = 4;</code>
   */
  ru.alfabank.alfagen.censor.transformation.contract.MessageListOrBuilder getMessagesOrBuilder();

  /**
   * <code>int32 max_completion_tokens = 5;</code>
   * @return The maxCompletionTokens.
   */
  int getMaxCompletionTokens();
}
