// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: censor_check.proto
// Protobuf Java Version: 4.32.0

package ru.alfabank.alfagen.censor.transformation.contract;

@com.google.protobuf.Generated
public interface CensorCheckResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:censor_check.CensorCheckResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Значения: "internal" (внутренний) или "external" (внешний)
   * </pre>
   *
   * <code>string accessDestination = 1;</code>
   * @return The accessDestination.
   */
  java.lang.String getAccessDestination();
  /**
   * <pre>
   * Значения: "internal" (внутренний) или "external" (внешний)
   * </pre>
   *
   * <code>string accessDestination = 1;</code>
   * @return The bytes for accessDestination.
   */
  com.google.protobuf.ByteString
      getAccessDestinationBytes();

  /**
   * <code>string systemId = 2;</code>
   * @return The systemId.
   */
  java.lang.String getSystemId();
  /**
   * <code>string systemId = 2;</code>
   * @return The bytes for systemId.
   */
  com.google.protobuf.ByteString
      getSystemIdBytes();

  /**
   * <code>string messageId = 3;</code>
   * @return The messageId.
   */
  java.lang.String getMessageId();
  /**
   * <code>string messageId = 3;</code>
   * @return The bytes for messageId.
   */
  com.google.protobuf.ByteString
      getMessageIdBytes();

  /**
   * <code>.censor_check.MessageList messages = 4;</code>
   * @return Whether the messages field is set.
   */
  boolean hasMessages();
  /**
   * <code>.censor_check.MessageList messages = 4;</code>
   * @return The messages.
   */
  ru.alfabank.alfagen.censor.transformation.contract.MessageList getMessages();
  /**
   * <code>.censor_check.MessageList messages = 4;</code>
   */
  ru.alfabank.alfagen.censor.transformation.contract.MessageListOrBuilder getMessagesOrBuilder();

  /**
   * <code>int32 max_completion_tokens = 5;</code>
   * @return The maxCompletionTokens.
   */
  int getMaxCompletionTokens();

  /**
   * <code>string risk_level = 6;</code>
   * @return The riskLevel.
   */
  java.lang.String getRiskLevel();
  /**
   * <code>string risk_level = 6;</code>
   * @return The bytes for riskLevel.
   */
  com.google.protobuf.ByteString
      getRiskLevelBytes();

  /**
   * <code>repeated .censor_check.Topic topics = 7;</code>
   */
  java.util.List<ru.alfabank.alfagen.censor.transformation.contract.Topic> 
      getTopicsList();
  /**
   * <code>repeated .censor_check.Topic topics = 7;</code>
   */
  ru.alfabank.alfagen.censor.transformation.contract.Topic getTopics(int index);
  /**
   * <code>repeated .censor_check.Topic topics = 7;</code>
   */
  int getTopicsCount();
  /**
   * <code>repeated .censor_check.Topic topics = 7;</code>
   */
  java.util.List<? extends ru.alfabank.alfagen.censor.transformation.contract.TopicOrBuilder> 
      getTopicsOrBuilderList();
  /**
   * <code>repeated .censor_check.Topic topics = 7;</code>
   */
  ru.alfabank.alfagen.censor.transformation.contract.TopicOrBuilder getTopicsOrBuilder(
      int index);

  /**
   * <code>string explanation = 8;</code>
   * @return The explanation.
   */
  java.lang.String getExplanation();
  /**
   * <code>string explanation = 8;</code>
   * @return The bytes for explanation.
   */
  com.google.protobuf.ByteString
      getExplanationBytes();
}
