// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: censor_check.proto
// Protobuf Java Version: 4.32.0

package ru.alfabank.alfagen.censor.transformation.contract;

@com.google.protobuf.Generated
public interface MessageListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:censor_check.MessageList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .censor_check.MessageText texts = 1;</code>
   */
  java.util.List<ru.alfabank.alfagen.censor.transformation.contract.MessageText> 
      getTextsList();
  /**
   * <code>repeated .censor_check.MessageText texts = 1;</code>
   */
  ru.alfabank.alfagen.censor.transformation.contract.MessageText getTexts(int index);
  /**
   * <code>repeated .censor_check.MessageText texts = 1;</code>
   */
  int getTextsCount();
  /**
   * <code>repeated .censor_check.MessageText texts = 1;</code>
   */
  java.util.List<? extends ru.alfabank.alfagen.censor.transformation.contract.MessageTextOrBuilder> 
      getTextsOrBuilderList();
  /**
   * <code>repeated .censor_check.MessageText texts = 1;</code>
   */
  ru.alfabank.alfagen.censor.transformation.contract.MessageTextOrBuilder getTextsOrBuilder(
      int index);
}
