// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: censor_check.proto
// Protobuf Java Version: 4.32.0

package ru.alfabank.alfagen.censor.transformation.contract;

@com.google.protobuf.Generated
public interface MessageTextOrBuilder extends
    // @@protoc_insertion_point(interface_extends:censor_check.MessageText)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string content = 1;</code>
   * @return The content.
   */
  java.lang.String getContent();
  /**
   * <code>string content = 1;</code>
   * @return The bytes for content.
   */
  com.google.protobuf.ByteString
      getContentBytes();

  /**
   * <pre>
   * Значения: "system" | "user" | "assistant"
   * </pre>
   *
   * <code>string role = 2;</code>
   * @return The role.
   */
  java.lang.String getRole();
  /**
   * <pre>
   * Значения: "system" | "user" | "assistant"
   * </pre>
   *
   * <code>string role = 2;</code>
   * @return The bytes for role.
   */
  com.google.protobuf.ByteString
      getRoleBytes();
}
