// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: censor_check.proto
// Protobuf Java Version: 4.32.0

package ru.alfabank.alfagen.censor.transformation.contract;

/**
 * Protobuf type {@code censor_check.MessageList}
 */
@com.google.protobuf.Generated
public final class MessageList extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:censor_check.MessageList)
    MessageListOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 32,
      /* patch= */ 0,
      /* suffix= */ "",
      MessageList.class.getName());
  }
  // Use MessageList.newBuilder() to construct.
  private MessageList(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private MessageList() {
    texts_ = java.util.Collections.emptyList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ru.alfabank.alfagen.censor.transformation.contract.CensorCheck.internal_static_censor_check_MessageList_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ru.alfabank.alfagen.censor.transformation.contract.CensorCheck.internal_static_censor_check_MessageList_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ru.alfabank.alfagen.censor.transformation.contract.MessageList.class, ru.alfabank.alfagen.censor.transformation.contract.MessageList.Builder.class);
  }

  public static final int TEXTS_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private java.util.List<ru.alfabank.alfagen.censor.transformation.contract.MessageText> texts_;
  /**
   * <code>repeated .censor_check.MessageText texts = 1;</code>
   */
  @java.lang.Override
  public java.util.List<ru.alfabank.alfagen.censor.transformation.contract.MessageText> getTextsList() {
    return texts_;
  }
  /**
   * <code>repeated .censor_check.MessageText texts = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends ru.alfabank.alfagen.censor.transformation.contract.MessageTextOrBuilder> 
      getTextsOrBuilderList() {
    return texts_;
  }
  /**
   * <code>repeated .censor_check.MessageText texts = 1;</code>
   */
  @java.lang.Override
  public int getTextsCount() {
    return texts_.size();
  }
  /**
   * <code>repeated .censor_check.MessageText texts = 1;</code>
   */
  @java.lang.Override
  public ru.alfabank.alfagen.censor.transformation.contract.MessageText getTexts(int index) {
    return texts_.get(index);
  }
  /**
   * <code>repeated .censor_check.MessageText texts = 1;</code>
   */
  @java.lang.Override
  public ru.alfabank.alfagen.censor.transformation.contract.MessageTextOrBuilder getTextsOrBuilder(
      int index) {
    return texts_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < texts_.size(); i++) {
      output.writeMessage(1, texts_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < texts_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, texts_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ru.alfabank.alfagen.censor.transformation.contract.MessageList)) {
      return super.equals(obj);
    }
    ru.alfabank.alfagen.censor.transformation.contract.MessageList other = (ru.alfabank.alfagen.censor.transformation.contract.MessageList) obj;

    if (!getTextsList()
        .equals(other.getTextsList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getTextsCount() > 0) {
      hash = (37 * hash) + TEXTS_FIELD_NUMBER;
      hash = (53 * hash) + getTextsList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ru.alfabank.alfagen.censor.transformation.contract.MessageList parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ru.alfabank.alfagen.censor.transformation.contract.MessageList parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ru.alfabank.alfagen.censor.transformation.contract.MessageList parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ru.alfabank.alfagen.censor.transformation.contract.MessageList parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ru.alfabank.alfagen.censor.transformation.contract.MessageList parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ru.alfabank.alfagen.censor.transformation.contract.MessageList parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ru.alfabank.alfagen.censor.transformation.contract.MessageList parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static ru.alfabank.alfagen.censor.transformation.contract.MessageList parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static ru.alfabank.alfagen.censor.transformation.contract.MessageList parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static ru.alfabank.alfagen.censor.transformation.contract.MessageList parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ru.alfabank.alfagen.censor.transformation.contract.MessageList parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static ru.alfabank.alfagen.censor.transformation.contract.MessageList parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ru.alfabank.alfagen.censor.transformation.contract.MessageList prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code censor_check.MessageList}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:censor_check.MessageList)
      ru.alfabank.alfagen.censor.transformation.contract.MessageListOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ru.alfabank.alfagen.censor.transformation.contract.CensorCheck.internal_static_censor_check_MessageList_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ru.alfabank.alfagen.censor.transformation.contract.CensorCheck.internal_static_censor_check_MessageList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ru.alfabank.alfagen.censor.transformation.contract.MessageList.class, ru.alfabank.alfagen.censor.transformation.contract.MessageList.Builder.class);
    }

    // Construct using ru.alfabank.alfagen.censor.transformation.contract.MessageList.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (textsBuilder_ == null) {
        texts_ = java.util.Collections.emptyList();
      } else {
        texts_ = null;
        textsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ru.alfabank.alfagen.censor.transformation.contract.CensorCheck.internal_static_censor_check_MessageList_descriptor;
    }

    @java.lang.Override
    public ru.alfabank.alfagen.censor.transformation.contract.MessageList getDefaultInstanceForType() {
      return ru.alfabank.alfagen.censor.transformation.contract.MessageList.getDefaultInstance();
    }

    @java.lang.Override
    public ru.alfabank.alfagen.censor.transformation.contract.MessageList build() {
      ru.alfabank.alfagen.censor.transformation.contract.MessageList result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public ru.alfabank.alfagen.censor.transformation.contract.MessageList buildPartial() {
      ru.alfabank.alfagen.censor.transformation.contract.MessageList result = new ru.alfabank.alfagen.censor.transformation.contract.MessageList(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(ru.alfabank.alfagen.censor.transformation.contract.MessageList result) {
      if (textsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          texts_ = java.util.Collections.unmodifiableList(texts_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.texts_ = texts_;
      } else {
        result.texts_ = textsBuilder_.build();
      }
    }

    private void buildPartial0(ru.alfabank.alfagen.censor.transformation.contract.MessageList result) {
      int from_bitField0_ = bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ru.alfabank.alfagen.censor.transformation.contract.MessageList) {
        return mergeFrom((ru.alfabank.alfagen.censor.transformation.contract.MessageList)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ru.alfabank.alfagen.censor.transformation.contract.MessageList other) {
      if (other == ru.alfabank.alfagen.censor.transformation.contract.MessageList.getDefaultInstance()) return this;
      if (textsBuilder_ == null) {
        if (!other.texts_.isEmpty()) {
          if (texts_.isEmpty()) {
            texts_ = other.texts_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureTextsIsMutable();
            texts_.addAll(other.texts_);
          }
          onChanged();
        }
      } else {
        if (!other.texts_.isEmpty()) {
          if (textsBuilder_.isEmpty()) {
            textsBuilder_.dispose();
            textsBuilder_ = null;
            texts_ = other.texts_;
            bitField0_ = (bitField0_ & ~0x00000001);
            textsBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 internalGetTextsFieldBuilder() : null;
          } else {
            textsBuilder_.addAllMessages(other.texts_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              ru.alfabank.alfagen.censor.transformation.contract.MessageText m =
                  input.readMessage(
                      ru.alfabank.alfagen.censor.transformation.contract.MessageText.parser(),
                      extensionRegistry);
              if (textsBuilder_ == null) {
                ensureTextsIsMutable();
                texts_.add(m);
              } else {
                textsBuilder_.addMessage(m);
              }
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.util.List<ru.alfabank.alfagen.censor.transformation.contract.MessageText> texts_ =
      java.util.Collections.emptyList();
    private void ensureTextsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        texts_ = new java.util.ArrayList<ru.alfabank.alfagen.censor.transformation.contract.MessageText>(texts_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        ru.alfabank.alfagen.censor.transformation.contract.MessageText, ru.alfabank.alfagen.censor.transformation.contract.MessageText.Builder, ru.alfabank.alfagen.censor.transformation.contract.MessageTextOrBuilder> textsBuilder_;

    /**
     * <code>repeated .censor_check.MessageText texts = 1;</code>
     */
    public java.util.List<ru.alfabank.alfagen.censor.transformation.contract.MessageText> getTextsList() {
      if (textsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(texts_);
      } else {
        return textsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .censor_check.MessageText texts = 1;</code>
     */
    public int getTextsCount() {
      if (textsBuilder_ == null) {
        return texts_.size();
      } else {
        return textsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .censor_check.MessageText texts = 1;</code>
     */
    public ru.alfabank.alfagen.censor.transformation.contract.MessageText getTexts(int index) {
      if (textsBuilder_ == null) {
        return texts_.get(index);
      } else {
        return textsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .censor_check.MessageText texts = 1;</code>
     */
    public Builder setTexts(
        int index, ru.alfabank.alfagen.censor.transformation.contract.MessageText value) {
      if (textsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTextsIsMutable();
        texts_.set(index, value);
        onChanged();
      } else {
        textsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .censor_check.MessageText texts = 1;</code>
     */
    public Builder setTexts(
        int index, ru.alfabank.alfagen.censor.transformation.contract.MessageText.Builder builderForValue) {
      if (textsBuilder_ == null) {
        ensureTextsIsMutable();
        texts_.set(index, builderForValue.build());
        onChanged();
      } else {
        textsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .censor_check.MessageText texts = 1;</code>
     */
    public Builder addTexts(ru.alfabank.alfagen.censor.transformation.contract.MessageText value) {
      if (textsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTextsIsMutable();
        texts_.add(value);
        onChanged();
      } else {
        textsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .censor_check.MessageText texts = 1;</code>
     */
    public Builder addTexts(
        int index, ru.alfabank.alfagen.censor.transformation.contract.MessageText value) {
      if (textsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTextsIsMutable();
        texts_.add(index, value);
        onChanged();
      } else {
        textsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .censor_check.MessageText texts = 1;</code>
     */
    public Builder addTexts(
        ru.alfabank.alfagen.censor.transformation.contract.MessageText.Builder builderForValue) {
      if (textsBuilder_ == null) {
        ensureTextsIsMutable();
        texts_.add(builderForValue.build());
        onChanged();
      } else {
        textsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .censor_check.MessageText texts = 1;</code>
     */
    public Builder addTexts(
        int index, ru.alfabank.alfagen.censor.transformation.contract.MessageText.Builder builderForValue) {
      if (textsBuilder_ == null) {
        ensureTextsIsMutable();
        texts_.add(index, builderForValue.build());
        onChanged();
      } else {
        textsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .censor_check.MessageText texts = 1;</code>
     */
    public Builder addAllTexts(
        java.lang.Iterable<? extends ru.alfabank.alfagen.censor.transformation.contract.MessageText> values) {
      if (textsBuilder_ == null) {
        ensureTextsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, texts_);
        onChanged();
      } else {
        textsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .censor_check.MessageText texts = 1;</code>
     */
    public Builder clearTexts() {
      if (textsBuilder_ == null) {
        texts_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        textsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .censor_check.MessageText texts = 1;</code>
     */
    public Builder removeTexts(int index) {
      if (textsBuilder_ == null) {
        ensureTextsIsMutable();
        texts_.remove(index);
        onChanged();
      } else {
        textsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .censor_check.MessageText texts = 1;</code>
     */
    public ru.alfabank.alfagen.censor.transformation.contract.MessageText.Builder getTextsBuilder(
        int index) {
      return internalGetTextsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .censor_check.MessageText texts = 1;</code>
     */
    public ru.alfabank.alfagen.censor.transformation.contract.MessageTextOrBuilder getTextsOrBuilder(
        int index) {
      if (textsBuilder_ == null) {
        return texts_.get(index);  } else {
        return textsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .censor_check.MessageText texts = 1;</code>
     */
    public java.util.List<? extends ru.alfabank.alfagen.censor.transformation.contract.MessageTextOrBuilder> 
         getTextsOrBuilderList() {
      if (textsBuilder_ != null) {
        return textsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(texts_);
      }
    }
    /**
     * <code>repeated .censor_check.MessageText texts = 1;</code>
     */
    public ru.alfabank.alfagen.censor.transformation.contract.MessageText.Builder addTextsBuilder() {
      return internalGetTextsFieldBuilder().addBuilder(
          ru.alfabank.alfagen.censor.transformation.contract.MessageText.getDefaultInstance());
    }
    /**
     * <code>repeated .censor_check.MessageText texts = 1;</code>
     */
    public ru.alfabank.alfagen.censor.transformation.contract.MessageText.Builder addTextsBuilder(
        int index) {
      return internalGetTextsFieldBuilder().addBuilder(
          index, ru.alfabank.alfagen.censor.transformation.contract.MessageText.getDefaultInstance());
    }
    /**
     * <code>repeated .censor_check.MessageText texts = 1;</code>
     */
    public java.util.List<ru.alfabank.alfagen.censor.transformation.contract.MessageText.Builder> 
         getTextsBuilderList() {
      return internalGetTextsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        ru.alfabank.alfagen.censor.transformation.contract.MessageText, ru.alfabank.alfagen.censor.transformation.contract.MessageText.Builder, ru.alfabank.alfagen.censor.transformation.contract.MessageTextOrBuilder> 
        internalGetTextsFieldBuilder() {
      if (textsBuilder_ == null) {
        textsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            ru.alfabank.alfagen.censor.transformation.contract.MessageText, ru.alfabank.alfagen.censor.transformation.contract.MessageText.Builder, ru.alfabank.alfagen.censor.transformation.contract.MessageTextOrBuilder>(
                texts_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        texts_ = null;
      }
      return textsBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:censor_check.MessageList)
  }

  // @@protoc_insertion_point(class_scope:censor_check.MessageList)
  private static final ru.alfabank.alfagen.censor.transformation.contract.MessageList DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ru.alfabank.alfagen.censor.transformation.contract.MessageList();
  }

  public static ru.alfabank.alfagen.censor.transformation.contract.MessageList getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<MessageList>
      PARSER = new com.google.protobuf.AbstractParser<MessageList>() {
    @java.lang.Override
    public MessageList parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<MessageList> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<MessageList> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public ru.alfabank.alfagen.censor.transformation.contract.MessageList getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

