// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: censor_check.proto
// Protobuf Java Version: 4.32.0

package ru.alfabank.alfagen.censor.transformation.contract;

@com.google.protobuf.Generated
public interface TopicOrBuilder extends
    // @@protoc_insertion_point(interface_extends:censor_check.Topic)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string topic = 1;</code>
   * @return The topic.
   */
  java.lang.String getTopic();
  /**
   * <code>string topic = 1;</code>
   * @return The bytes for topic.
   */
  com.google.protobuf.ByteString
      getTopicBytes();

  /**
   * <code>float confidence = 2;</code>
   * @return The confidence.
   */
  float getConfidence();
}
